### ISSUE TITLE
Bump minimum PHP version to 7.4

### ISSUE THREAD

**Issue by jcsilkey** [idiosyncratic-code/editorconfig-php#10]
Bump minimum PHP version to ~8~ 7.4

**Comment by sabbelasichon** [comment]
Why PHP8 as minimum version? Cannot use this library anymore if PHP 8 is required.

**Comment by sabbelasichon** [comment]
Sorry. Didn´t read your last comment. But still not sure if PHP 8 should be the minimum version right now.

**Comment by jcsilkey** [comment]
I am mostly working with PHP 8 now (aside from my day job, which is a whole different story altogether), hence my desire to bump the minimum version to 8. I'm open to reconsidering though, especially if the only other people using the library besides me are on PHP 7. :)

Would there be any concerns with bumping to 7.4?

**Comment by sabbelasichon** [comment]
7.4 is absolutely fine.

**Comment by jcsilkey** [comment]
We'll go with 7.4 as the minimum version.

**Comment by a-r-m-i-n** [comment]
The higher the requirements are, the less accessible your library is. As long as you don't require any PHP 7.4 features, I would wait till the support is officially outdated, which is the case at 6th Dec 2021 for PHP 7.3 and at 28th Nov 2022 for PHP 7.4.

But, it is your free choice :)

**Comment by staabm** [comment]
I agree that bumping the min php version without a need just prevents wide adoption of the lib without further benefit.

especially on ubuntu lts and similar setups php versions are "rather outdated"

**Comment by jcsilkey** [comment]
Keeping it at 7.3 for the time being, will revisit after the next PHP release.
