### ISSUE TITLE
"root = true" in child .editorconfig files is getting ignored

### ISSUE THREAD

**Issue by a-r-m-i-n** [idiosyncratic-code/editorconfig-php#11]
Hi,
I think I discovered a bug, with respecting set `root = true` in .editorconfig files. Regarding the docs it should behave like this:

> A search for .editorconfig files will stop if the root filepath is reached or an EditorConfig file with root=true is found.

But this flag seems to be ignored. 

What I'm expecting:
- it reset all declarations
- does not perform validation on any file within

Without `root=true` I would expect, the current behaviour of merging the values.

Thanks for this great lib!

**Comment by a-r-m-i-n** [comment]
The child .editorconfig with `root=true` set, only should get evaluated, when it is actually located in current working directory. To achieve this, we need to know the root path of the initial call. I would suggest to extend `\Idiosyncratic\EditorConfig\EditorConfig` by an `public function __constructor(?string $rootPath = null)` method.

**Comment by a-r-m-i-n** [comment]
This works properly for me. But I did not covered it with tests nor docs, in my merge request.

**Comment by a-r-m-i-n** [comment]
Hello, someone there? 🙋

**Comment by jcsilkey** [comment]
The current behavior is correct per the EC spec.

>When a filename is given to EditorConfig a search is performed in the **directory of the given file** and all parent directories for an EditorConfig file (named “.editorconfig” by default). Non-existing directories are treated as if they exist and are empty. All found EditorConfig files are searched for sections with section names matching the given filename. The search shall stop if an EditorConfig file is found with the root key set to true in the preamble or when reaching the root filesystem directory.
>
>Files are read top to bottom and the most recent rules found take precedence. If multiple EditorConfig files have matching sections, the rules from the closer EditorConfig file are read last, so pairs in closer files take precedence.

- Searching for EC files is performed starting from the location of the file being edited, not the current working directory.
- Searching stops once the root of the file system is reached or an EC file is found with `root=true`.
- Values from all EC files are merged starting from the root and ending with the EC file closest to the file being edited.

**Comment by a-r-m-i-n** [comment]
Okay. Thanks for the response. I'm not sure what my issue was two weeks ago... After your explaination I've tested some cases and indeed, all works fine. Sorry for this false alert.
