### ISSUE TITLE
Comments for conditions result in PHP warning

### ISSUE THREAD

**Issue by a-r-m-i-n** [idiosyncratic-code/editorconfig-php#3]
When you comment a condition out in .editorconfig, like:

```
#[*.md]
```

The following warning is thrown:
> PHP Warning:  syntax error, unexpected END_OF_LINE, expecting '=' in Unknown on line 40
> in /var/www/html/vendor/idiosyncratic/editorconfig/src/EditorConfigFile.php on line 130

It only happens when a comment is on the condition part. This works as expected:
```
[*.md]
#indent_size = 4
```

Thanks!

**Comment by jcsilkey** [comment]
Ugh, looks like this is due to differences between the editorconfig "INI-like" format and actual INI format. INI files only allow `;`  comments, but EC also allows `#`, and I'm using `parse_ini_string`.
