### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sabbelasichon** [idiosyncratic-code/editorconfig-php#9]
Would you mind to create a new release after #6 is merged. That would be really awesome, not relying on master. Thank you very much.

**Comment by jcsilkey** [comment]
Will do. I didn't have time last night to look it over, but I'll check it as soon as I'm done working for the day.

FYI, I'll also be renaming `master` to `main` after this is closed.

**Comment by jcsilkey** [comment]
One last comment, after I tag a new release I'm likely going to bump the required PHP version to 8 for the next release after.

**Comment by sabbelasichon** [comment]
Would you mind to create the release. All changes are working well in the wild ;-)

**Comment by jcsilkey** [comment]
Released.

**Comment by sabbelasichon** [comment]
Thanks a lot. Hope you like some more stars on your Repository ;-)
